// AUTO-GENERATED by pnpm conformance:gen. Do not edit by hand.
// Each capability declared in src/main/capabilities/ gets a test stub.
// pnpm conformance:check will fail if any stub remains unfilled.
import { describe, it } from 'vitest';

describe('headhunter', () => {
  it.todo('headhunter.upload_candidate: POST /v1/headhunter/candidates');
  it.todo('headhunter.recommend_candidate: POST /v1/headhunter/recommendations');
  it.todo('headhunter.withdraw_recommendation: POST /v1/headhunter/recommendations/:id/withdraw');
  it.todo('headhunter.publish_to_pool: POST /v1/headhunter/candidates/:id/publish-to-pool');
  it.todo('headhunter.list_recommendations: GET /v1/headhunter/recommendations');
  it.todo('headhunter.list_candidates: GET /v1/headhunter/candidates');
  it.todo('headhunter.create_job: POST /v1/headhunter/jobs');
  it.todo('headhunter.list_jobs: GET /v1/headhunter/jobs');
});

describe('employer', () => {
  it.todo('employer.create_placement: POST /v1/employer/placements');
  it.todo('employer.list_placements: GET /v1/employer/placements');
  it.todo('employer.create_job: POST /v1/employer/jobs');
  it.todo('employer.list_jobs: GET /v1/employer/jobs');
  it.todo('employer.browse_talent: GET /v1/employer/talent');
  it.todo('employer.express_interest: POST /v1/employer/recommendations/:id/express-interest');
  it.todo('employer.unlock_contact: POST /v1/employer/recommendations/:id/unlock-contact');
  it.todo('employer.list_pending_claims: GET /v1/employer/pending-claims');
  it.todo('employer.claim_job: POST /v1/employer/claim-jobs/:id');
  it.todo('employer.reject_job: POST /v1/employer/reject-jobs/:id');
});

describe('candidate', () => {
  it.todo('candidate.view_opportunities: GET /v1/candidate/opportunities');
  it.todo('candidate.access_log: GET /v1/candidate/access-log');
  it.todo('candidate.export_my_data: GET /v1/candidate/export-my-data');
  it.todo('candidate.approve_unlock: POST /v1/candidate/recommendations/:id/approve-unlock');
  it.todo('candidate.reject_unlock: POST /v1/candidate/recommendations/:id/reject-unlock');
  it.todo('candidate.delete_my_data: POST /v1/candidate/delete-my-data');
});

describe('admin', () => {
  it.todo('admin.ping: GET /v1/admin/ping');
  it.todo('admin.dashboard_stats: GET /v1/admin/dashboard/stats');
  it.todo('admin.list_users: GET /v1/admin/users');
  it.todo('admin.suspend_user: POST /v1/admin/users/:id/suspend');
  it.todo('admin.unsuspend_user: POST /v1/admin/users/:id/unsuspend');
  it.todo('admin.adjust_user_quota: POST /v1/admin/users/:id/adjust-quota');
  it.todo('admin.list_candidates: GET /v1/admin/candidates');
  it.todo('admin.remove_from_pool: POST /v1/admin/candidates/:id/remove-from-pool');
  it.todo('admin.audit_log: GET /v1/admin/audit');
  it.todo('admin.webhook_dead_letter: GET /v1/admin/webhooks/dead-letter');
  it.todo('admin.retry_webhook: POST /v1/admin/webhooks/:id/retry');
  it.todo('admin.rate_limit_buckets: GET /v1/admin/rate-limit/buckets');
  it.todo('admin.clear_user_rate_limit: POST /v1/admin/rate-limit/users/:id/clear');
  it.todo('admin.get_config: GET /v1/admin/config');
  it.todo('admin.put_config: PUT /v1/admin/config/:key');
  it.todo('admin.list_placements: GET /v1/admin/placements');
  it.todo('admin.mark_placement_paid: POST /v1/admin/placements/:id/mark-paid');
  it.todo('admin.cancel_placement: POST /v1/admin/placements/:id/cancel');
  it.todo('admin.placements_summary: GET /v1/admin/placements/summary');
  it.todo('admin.admin_log: GET /v1/admin/admin-log');
});

describe('auth', () => {
  it.todo('auth.register: POST /v1/auth/register');
  it.todo('auth.rotate_key: POST /v1/auth/rotate-key');
});
