import os, re
out = []
add = out.append
add("# Hunter Platform - Features Reference")
add("")
add("> Single source of truth for what the platform exposes. Counts are")
add("> 141 REST endpoints and 86 declared capabilities (R1.C2 + R1.C3 + R1.C4 +")
add("> T10 close, deployed on qing3.top). Backed by 25 schema migrations.")
add(">")
add("> Last updated 2026-07-15. Generated from src/main/routes/*.ts and")
add("> src/main/capabilities/*.ts. Regenerate via python3 scripts/gen-features-doc.py.")
add("")
add("---")
add("")
add("## 1. Top-level architecture")
add("")
add("Two deployment targets: this Node.js API (prod qing3.top via Linode) and")
add("the admin-web (React 18 + Vite, served as static SPA). All interaction is")
add("plain HTTP/JSON; there is no desktop client, no IPC, no proprietary protocol.")
add("")
add("Routes: 141 endpoints across 15 router files.")
add("Capabilities: 86 declared (8 role sets).")
add("Schema: 25 migrations applied on prod.")
add("")
add("---")
add("")
add("## 2. REST endpoints by router")
add("")
add("Total: 141 endpoints across 15 router files. Mount prefixes reflect")
add("how the server in src/main/server.ts attaches them.")
add("")
total_routes = 0
for f in sorted(os.listdir('src/main/routes')):
    if not f.endswith('.ts'): continue
    text = open('src/main/routes/' + f).read()
    methods = re.findall(r"router\.(get|post|put|delete|patch)\(\s*['\"`]([^'\"`]+)['\"`]", text)
    if not methods: continue
    n = len(methods)
    total_routes += n
    add("### src/main/routes/" + f + "  (" + str(n) + " endpoints)")
    add("")
    add("| Method | Path |")
    add("|---|---|")
    for m, p in methods:
        add("| " + m.upper() + " | `" + p + "` |")
    add("")
add("Total: " + str(total_routes) + " endpoints.")
add("")
add("---")
add("")
add("## 3. Declared capabilities by role")
add("")
add("Capabilities are the typed contract. Each maps to a route + method,")
add("resolved at request time by the capability-resolver middleware.")
add("Total: 86 capabilities across 8 role sets.")
add("")
total_caps = 0
for f in sorted(os.listdir('src/main/capabilities')):
    if not f.endswith('.ts') or f in ('types.ts', 'index.ts'): continue
    text = open('src/main/capabilities/' + f).read()
    role_m = re.search(r"role:\s*'([^']+)'", text)
    if not role_m: continue
    role = role_m.group(1)
    name_matches = re.findall(r"name:\s*'([^']+)',", text)
    if not name_matches: continue
    n = len(name_matches)
    total_caps += n
    add("### Role `" + role + "`  (" + str(n) + " capabilities, src/main/capabilities/" + f + ")")
    add("")
    for n2 in name_matches:
        add("- `" + n2 + "`")
    add("")
add("Total: " + str(total_caps) + " capabilities.")
add("")
add("---")
add("")
add("## 4. Authentication & access modes")
add("")
add("Two bearer-token modes (R1.C2 dual-track):")
add("")
add("| Mode | Token | TTL | Role switch |")
add("|---|---|---|---|")
add("| API key (legacy) | `Bearer hp_live_xxx` | indefinite | none (uses registered user_type) |")
add("| Session (R1.C2) | `Bearer sess_xxx` | 168h sliding | `X-Active-Role: pm|hr|candidate` |")
add("")
add("Special cases:")
add("- Admin: per-admin `hp_admin_xxx` key, separate auth path")
add("- Webhook inbox (R1.C3): HMAC-verified, no bearer")
add("- Marketplace public: no auth")
add("- Landing: static HTML, no auth")
add("")
add("---")
add("")
add("## 5. Per-router role gates (T10)")
add("")
add("| Router | Allowed role |")
add("|---|---|")
add("| /v1/pm | pm |")
add("| /v1/employer | pm |")
add("| /v1/employer-panel | pm |")
add("| /v1/headhunter | hr |")
add("| /v1/headhunter-workspace | hr |")
add("| /v1/candidate | candidate |")
add("| /v1/admin | admin (separate) |")
add("| /v1/webhooks | HMAC |")
add("")
add("Cross-role access returns 403 FORBIDDEN with message 'Role X not allowed here'.")
add("")
add("---")
add("")
add("## 6. External skill name aliases (R1.C4)")
add("")
add("| ow-recruit skill | hunter-platform canonical | HTTP |")
add("|---|---|---|")
add("| ow_recruit.advance_candidate | pm.select_staffing_plan | POST /v1/pm/staffing-plans/:id/select |")
add("| ow_recruit.send_message | candidate_portal.messages.send | POST /v1/candidate-portal/messages |")
add("| ow_recruit.sync_project_to_erp | pm.update_project | PATCH /v1/pm/projects/:id |")
add("")
add("Add a new alias by appending `aliases: [...]` to the capability declaration.")
add("")
add("---")
add("")
add("## 7. Recent migrations (R1 era)")
add("")
add("| Version | Description |")
add("|---|---|")
add("| v025 | Candidate Portal (otp_codes, messages, applications) |")
add("| v026 | Recommendation flow (nullable headhunter_id, status extensions) |")
add("| v027 | Hunter workspace (tasks + kanban) |")
add("| v028 | PM Workbench (projects, positions, plans, decompositions, matches, notes) |")
add("| v029 | Extend users.user_type CHECK to allow pm |")
add("| v030 | PM Sandbox: link recommendations to project_positions + stage_entered_at |")
add("| v031 | R1.C2: session table + user_role multi-role + role enum rename (headhunter->hr, employer->pm) |")
add("| v032 | R1.C3: webhook inbox dedup (`webhook_inbox_deliveries` with UNIQUE(endpoint, body_hash)) |")
add("")
add("Pre-R1 (still active on prod): v001-v016 + v024.")
add("")
add("---")
add("")
add("## 8. Operational surfaces (admin-web)")
add("")
add("The admin-web/ package is a React 18 + Vite SPA. Routes are guarded")
add("by PrivateRoute. Pages:")
add("")
add("| Path | Purpose |")
add("|---|---|")
add("| / (login) | Admin login |")
add("| /admin | Dashboard |")
add("| /admin/users (/+ /:id, /:id/timeline) | User list / detail / action history |")
add("| /admin/candidates (+ variants) | Candidate list / detail / timeline |")
add("| /admin/jobs (+ variants) | Job list / detail / timeline |")
add("| /admin/recommendations (+ variants) | Recommendation list / detail / timeline |")
add("| /admin/placements | Placements + mark-paid / cancel |")
add("| /admin/audit | Audit log (action_history) |")
add("| /admin/webhooks/dead-letter | Failed outbound webhooks (DLQ) |")
add("| /admin/settings | Config (key/value) |")
add("| /admin/rate-limit (R2.5, new) | Rate-limit & quota dashboard |")
add("| /admin/profile | Admin profile / password change |")
add("")
add("---")
add("")
add("## 9. Where to look next")
add("")
add("- Live HTTP contract -> GET /v1/openapi.json (150 routes)")
add("- Agent-facing guide -> docs/superpowers/skill.md (1668 lines)")
add("- Production deploy process -> docs/OPERATIONS.md")
add("- Project memory + runbook -> docs/PROJECT_MEMORY.md")
add("- Source of truth for declared capabilities -> src/main/capabilities/")
add("- History of archived design -> docs/archive/2026-q1/")
add("")
add("When this doc and the code disagree, the code wins. Update as part")
add("of any feature PR that changes the totals above.")
print('\n'.join(out))
