// scripts/generate-skill-md-scenarios.ts
/**
 * pnpm conformance:gen — read src/main/capabilities/ and emit a baseline
 * scenario file at tests/integration/skill-md-conformance/_generated.test.ts.
 *
 * The generated file has a placeholder `it.todo(...)` for every declared
 * capability. The developer is expected to either:
 *   (a) write a real test that fills the placeholder, OR
 *   (b) leave the placeholder as a contract gap (conformance:check will
 *       fail CI until filled, UNLESS the only unfilled stubs are inside
 *       this auto-generated _generated.test.ts).
 *
 * Run `pnpm conformance:check` to verify all capabilities have a real test
 * somewhere in skill-md-conformance/ (excluding this file).
 *
 * Output is deterministic: roles sorted alphabetically, capabilities in
 * declaration order. Running the generator twice yields byte-identical
 * output so CI diffs are reviewable.
 */
import fs from 'node:fs';
import path from 'node:path';
import { getAllCapabilitySets } from '../src/main/capabilities/index.js';

const OUT_PATH = path.join(
  __dirname,
  '../tests/integration/skill-md-conformance/_generated.test.ts',
);

function main(): void {
  const sets = getAllCapabilitySets();
  const sortedSets = [...sets].sort((a, b) => a.role.localeCompare(b.role));

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by pnpm conformance:gen. DO NOT EDIT.');
  lines.push('// Each capability declared in src/main/capabilities/ gets a test stub.');
  lines.push("// pnpm conformance:check ignores this file when counting coverage,");
  lines.push("// so stubs here are allowed; stubs elsewhere will fail CI.");
  lines.push("import { describe, it } from 'vitest';");
  lines.push('');

  for (const set of sortedSets) {
    lines.push(`describe('${set.role}', () => {`);
    for (const c of set.capabilities) {
      const todo = `  it.todo('${c.name}: ${c.method} ${c.path}');`;
      lines.push(todo);
    }
    lines.push('});');
    lines.push('');
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  const totalCaps = sortedSets.reduce((n, s) => n + s.capabilities.length, 0);
  console.log(
    `Generated ${OUT_PATH} with ${sortedSets.length} describe blocks and ${totalCaps} capability stubs.`,
  );
}

main();
