// scripts/generate-skill-md-scenarios.ts
/**
 * pnpm conformance:gen — read src/main/capabilities/ and emit a baseline
 * scenario file at tests/integration/skill-md-conformance/_generated.test.ts.
 *
 * Smart skip: scans every other `*.test.ts` in the same directory and
 * skips emitting a stub for any capability that is already covered by a
 * REAL test there (real = NOT inside an `it.todo(...)` line, mirroring
 * what `pnpm conformance:check` counts).
 *
 * The generated file shrinks over time as more capabilities get real
 * tests. Re-running the generator is idempotent and safe.
 *
 * Run `pnpm conformance:check` to verify all capabilities have coverage.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getAllCapabilitySets } from '../src/main/capabilities/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUT_PATH = path.join(
  __dirname,
  '../tests/integration/skill-md-conformance/_generated.test.ts',
);
const CONFORMANCE_DIR = path.join(
  __dirname,
  '../tests/integration/skill-md-conformance',
);

/** Strip `it.todo(...)` / `it.skip(...)` / `xit.todo(...)` lines so the
 *  scan only counts REAL test references, not the stubs this script generates. */
function stripStubs(src: string): string {
  return src
    .split('\n')
    .filter((line) => !/^\s*(?:it|xit|test)\.(?:todo|skip)\s*\(/.test(line))
    .join('\n');
}

/** Returns the set of capability names that are already covered by a real
 *  test in the conformance directory (excluding _generated.test.ts). */
function alreadyCovered(): Set<string> {
  const covered = new Set<string>();
  for (const file of fs.readdirSync(CONFORMANCE_DIR).filter(
    (f) => f.endsWith('.test.ts') && f !== '_generated.test.ts',
  )) {
    const raw = fs.readFileSync(path.join(CONFORMANCE_DIR, file), 'utf8');
    const src = stripStubs(raw);
    for (const set of getAllCapabilitySets()) {
      for (const cap of set.capabilities) {
        if (src.includes(cap.name) || src.includes(`${cap.method} ${cap.path}`)) {
          covered.add(cap.name);
        }
      }
    }
  }
  return covered;
}

function main(): void {
  const sets = getAllCapabilitySets();
  const sortedSets = [...sets].sort((a, b) => a.role.localeCompare(b.role));
  const covered = alreadyCovered();

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by pnpm conformance:gen. DO NOT EDIT.');
  lines.push('// Emits one `it.todo(...)` stub per capability NOT yet covered by');
  lines.push('// a real test in any other `*.test.ts` in this directory.');
  lines.push('// Re-run `pnpm conformance:gen` after writing real tests to shrink');
  lines.push('// the stub list. pnpm conformance:check passes when this file is');
  lines.push('// empty (or missing) — every cap has a real scenario.');
  lines.push("import { describe, it } from 'vitest';");
  lines.push('');

  let totalStubs = 0;
  for (const set of sortedSets) {
    const stubs = set.capabilities.filter((c) => !covered.has(c.name));
    if (stubs.length === 0) continue;  // skip roles with no remaining stubs
    lines.push(`describe('${set.role}', () => {`);
    for (const c of stubs) {
      const todo = `  it.todo('${c.name}: ${c.method} ${c.path}');`;
      lines.push(todo);
      totalStubs++;
    }
    lines.push('});');
    lines.push('');
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  const totalCaps = sortedSets.reduce((n, s) => n + s.capabilities.length, 0);
  const skipped = totalCaps - totalStubs;
  console.log(
    `Generated ${OUT_PATH}: ${totalStubs} stub${totalStubs === 1 ? '' : 's'}` +
    ` (skipped ${skipped} already-covered cap${skipped === 1 ? '' : 's'}; ` +
    `out of ${totalCaps} total).`,
  );
  if (totalStubs === 0) {
    console.log('✨ All capabilities have real tests — _generated.test.ts has zero stubs.');
  }
}

main();
