/**
 * pnpm conformance:gen — read src/main/capabilities/*.ts and emit a baseline
 * scenario file at tests/integration/skill-md-conformance/_generated.test.ts.
 *
 * The generated file has a placeholder `it.todo(...)` for every declared
 * capability. The developer is expected to either:
 *   (a) write a real test that fills the placeholder, OR
 *   (b) leave the placeholder as a contract gap (will fail CI until filled).
 *
 * Run `pnpm conformance:check` to verify no `it.todo` remain in
 * skill-md-conformance/. The check runs in CI.
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  getAllCapabilitySets,
} from '../src/main/capabilities/index.js';

const OUT_PATH = path.join(__dirname, '../tests/integration/skill-md-conformance/_generated.test.ts');

function main() {
  const sets = getAllCapabilitySets();
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by pnpm conformance:gen. Do not edit by hand.');
  lines.push('// Each capability declared in src/main/capabilities/ gets a test stub.');
  lines.push('// pnpm conformance:check will fail if any stub remains unfilled.');
  lines.push("import { describe, it } from 'vitest';");
  lines.push('');

  for (const set of sets) {
    lines.push(`describe('${set.role}', () => {`);
    for (const c of set.capabilities) {
      const todo = `  it.todo('${c.name}: ${c.method} ${c.path}');`;
      lines.push(todo);
    }
    lines.push('});');
    lines.push('');
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`Generated ${OUT_PATH} with ${sets.reduce((n, s) => n + s.capabilities.length, 0)} capability stubs.`);
}

main();