import { defineCapabilitySet } from './types.js';
import {
  PingResponseSchema, DashboardStatsResponseSchema, ListUsersResponseSchema,
  SuspendUserResponseSchema, UnsuspendUserResponseSchema, AdjustQuotaResponseSchema,
  ListCandidatesResponseSchema, RemoveFromPoolResponseSchema, AuditListResponseSchema,
  DeadLetterListResponseSchema, RetryWebhookResponseSchema,
  RateLimitBucketsResponseSchema, ClearRateLimitResponseSchema,
  ConfigGetResponseSchema, ConfigPutResponseSchema, AdminPlacementsListResponseSchema,
  MarkPaidResponseSchema, CancelPlacementResponseSchema,
  PlacementsSummaryResponseSchema, AdminLogListResponseSchema,
  ListJobsResponseSchema, ListRecommendationsResponseSchema,
  ListTimelineResponseSchema,
} from '../schemas/admin.js';

export const adminCapabilities = defineCapabilitySet({
  role: 'admin',
  capabilities: [
    {
      name: 'admin.ping',
      description: 'Admin 健康检查 ping。',
      method: 'GET', path: '/v1/admin/ping',
      response_schema: PingResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: [],
    },
    {
      name: 'admin.dashboard_stats',
      description: '平台总览统计(用户/候选人/job/placement 数)。',
      method: 'GET', path: '/v1/admin/dashboard/stats',
      response_schema: DashboardStatsResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.aggregate.stats'],
    },
    {
      name: 'admin.list_users',
      description: '列出所有用户(支持过滤 user_type / status)。',
      method: 'GET', path: '/v1/admin/users',
      response_schema: ListUsersResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.users.listAll'],
    },
    {
      name: 'admin.suspend_user',
      description: '暂停某个用户的账号。',
      method: 'POST', path: '/v1/admin/users/:id/suspend',
      response_schema: SuspendUserResponseSchema,
      quota_cost: 0,
      preconditions: ['flow.user.suspend'],
      effects: ['db.users.updateStatus(suspended)', 'admin_action_log: suspend_user'],
    },
    {
      name: 'admin.unsuspend_user',
      description: '恢复被暂停的账号。',
      method: 'POST', path: '/v1/admin/users/:id/unsuspend',
      response_schema: UnsuspendUserResponseSchema,
      quota_cost: 0,
      preconditions: ['flow.user.unsuspend'],
      effects: ['db.users.updateStatus(active)', 'admin_action_log: unsuspend_user'],
    },
    {
      name: 'admin.adjust_user_quota',
      description: '调整用户的每日配额上限。',
      method: 'POST', path: '/v1/admin/users/:id/adjust-quota',
      response_schema: AdjustQuotaResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.users.updateQuota', 'admin_action_log: adjust_quota'],
    },
    {
      name: 'admin.list_candidates',
      description: '列出所有脱敏候选人(管理员视图,含 PII 关联)。',
      method: 'GET', path: '/v1/admin/candidates',
      response_schema: ListCandidatesResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.candidates_anonymized.listAll'],
    },
    {
      name: 'admin.remove_from_pool',
      description: '把候选人从公共池移除(违规内容处理)。',
      method: 'POST', path: '/v1/admin/candidates/:id/remove-from-pool',
      response_schema: RemoveFromPoolResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.candidates_anonymized.update(is_public_pool=0)'],
    },
    {
      name: 'admin.audit_log',
      description: '查看平台 audit_log(谁在什么时间调用了什么 endpoint)。',
      method: 'GET', path: '/v1/admin/audit',
      response_schema: AuditListResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.unlock_audit.list'],
    },
    {
      name: 'admin.webhook_dead_letter',
      description: '列出 webhook dead-letter 队列(投递失败待重试的事件)。',
      method: 'GET', path: '/v1/admin/webhooks/dead-letter',
      response_schema: DeadLetterListResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.webhook_deliveries.listDeadLetter'],
    },
    {
      name: 'admin.retry_webhook',
      description: '手动重试 dead-letter 中的某个 webhook 投递。',
      method: 'POST', path: '/v1/admin/webhooks/:id/retry',
      response_schema: RetryWebhookResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.webhook_deliveries.update(status=pending)'],
    },
    {
      name: 'admin.rate_limit_buckets',
      description: '查看当前所有 rate-limit bucket 状态(per-user + per-second/minute/hour)。',
      method: 'GET', path: '/v1/admin/rate-limit/buckets',
      response_schema: RateLimitBucketsResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.rate_limit.listBuckets'],
    },
    {
      name: 'admin.clear_user_rate_limit',
      description: '清空某个用户的 rate-limit bucket(解除误限)。',
      method: 'POST', path: '/v1/admin/rate-limit/users/:id/clear',
      response_schema: ClearRateLimitResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.rate_limit.clearUser'],
    },
    {
      name: 'admin.get_config',
      description: '读取平台动态配置。',
      method: 'GET', path: '/v1/admin/config',
      response_schema: ConfigGetResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.config.getAll'],
    },
    {
      name: 'admin.put_config',
      description: '写入/覆盖平台动态配置项。',
      method: 'PUT', path: '/v1/admin/config/:key',
      response_schema: ConfigPutResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.config.set', 'admin_action_log: config_change'],
    },
    {
      name: 'admin.list_placements',
      description: '列出所有 placement 记录(管理员视图)。',
      method: 'GET', path: '/v1/admin/placements',
      response_schema: AdminPlacementsListResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.placements.listAll'],
    },
    {
      name: 'admin.mark_placement_paid',
      description: '把 placement 标记为已支付(财务确认)。',
      method: 'POST', path: '/v1/admin/placements/:id/mark-paid',
      response_schema: MarkPaidResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.placements.updateStatus(paid)'],
    },
    {
      name: 'admin.cancel_placement',
      description: '取消一个 placement(候选人未入职等异常情况)。',
      method: 'POST', path: '/v1/admin/placements/:id/cancel',
      response_schema: CancelPlacementResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.placements.updateStatus(cancelled)'],
    },
    {
      name: 'admin.placements_summary',
      description: 'placement 总览统计(count / pending / paid / cancelled / total revenue)。',
      method: 'GET', path: '/v1/admin/placements/summary',
      response_schema: PlacementsSummaryResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.placements.aggregate'],
    },
    {
      name: 'admin.admin_log',
      description: '查看 admin 操作日志(谁在什么时间做了什么管理动作)。',
      method: 'GET', path: '/v1/admin/admin-log',
      response_schema: AdminLogListResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.admin_action_log.list'],
    },
    {
      name: 'admin.list_jobs',
      description: '列出所有 jobs(含 employer_name),支持 status 筛选 + 关键词搜索。',
      method: 'GET', path: '/v1/admin/jobs',
      response_schema: ListJobsResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.jobs.listAll'],
    },
    {
      name: 'admin.list_recommendations',
      description: '列出所有 recommendations(含 job_title + headhunter_name),支持 status 筛选 + 关键词 + 时间范围。',
      method: 'GET', path: '/v1/admin/recommendations',
      response_schema: ListRecommendationsResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.recommendations.listAll'],
    },
    {
      name: 'admin.get_timeline',
      description: '获取 user/candidate/job/recommendation 的合并审计时间轴(UNION 3 表)。',
      method: 'GET', path: '/v1/admin/timeline/:type/:id',
      response_schema: ListTimelineResponseSchema,
      quota_cost: 0,
      preconditions: [],
      effects: ['db.audit.unionAll'],
    },
  ],
});