import { defineCapabilitySet } from './types.js';
import {
  CreatePlacementResponseSchema, ListPlacementsResponseSchema,
  CreateJobResponseSchema, ListMyJobsResponseSchema,
  BrowseTalentResponseSchema, ExpressInterestResponseSchema,
  UnlockContactResponseSchema, PendingClaimsResponseSchema,
  ClaimJobResponseSchema, RejectJobResponseSchema,
} from '../schemas/employer.js';
import { QUOTA_COSTS } from '../../shared/constants.js';

export const employerCapabilities = defineCapabilitySet({
  role: 'employer',
  capabilities: [
    {
      name: 'employer.create_placement',
      description: '创建 placement 记录(标记候选人入职成功,平台费按 commission_split 计算)。',
      method: 'POST', path: '/v1/employer/placements',
      response_schema: CreatePlacementResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"', 'flow.recommendation.place'],
      effects: ['db.placements.insert', 'webhook: placement_created'],
    },
    {
      name: 'employer.list_placements',
      description: '列出我创建的 placement 记录。',
      method: 'GET', path: '/v1/employer/placements',
      response_schema: ListPlacementsResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"'],
      effects: ['db.placements.listByUser'],
    },
    {
      name: 'employer.create_job',
      description: '创建 job(开放给猎头推荐候选人)。',
      method: 'POST', path: '/v1/employer/jobs',
      response_schema: CreateJobResponseSchema,
      quota_cost: QUOTA_COSTS.create_job,
      preconditions: ['user.status === "active"'],
      effects: ['consume_quota(5)', 'db.jobs.insert'],
    },
    {
      name: 'employer.list_jobs',
      description: '列出我创建过的所有 job。',
      method: 'GET', path: '/v1/employer/jobs',
      response_schema: ListMyJobsResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"'],
      effects: ['db.jobs.listByEmployer'],
    },
    {
      name: 'employer.browse_talent',
      description: '浏览公共池中的脱敏候选人(雇主可以预览行业/职级/年限)。',
      method: 'GET', path: '/v1/employer/talent',
      response_schema: BrowseTalentResponseSchema,
      quota_cost: QUOTA_COSTS.browse_talent,
      preconditions: ['user.status === "active"'],
      effects: ['consume_quota(1)', 'db.candidates_anonymized.listPublicPool'],
    },
    {
      name: 'employer.express_interest',
      description: '对某条 recommendation 表达兴趣(触发 unlock 请求,通知候选人)。',
      method: 'POST', path: '/v1/employer/recommendations/:id/express-interest',
      response_schema: ExpressInterestResponseSchema,
      quota_cost: QUOTA_COSTS.express_interest,
      preconditions: ['user.status === "active"', 'flow.recommendation.express_interest'],
      effects: ['consume_quota(3)', 'webhook: notify_unlock_request'],
    },
    {
      name: 'employer.unlock_contact',
      description: '解锁候选人联系方式(候选人已 approve_unlock 后才能调)。',
      method: 'POST', path: '/v1/employer/recommendations/:id/unlock-contact',
      response_schema: UnlockContactResponseSchema,
      quota_cost: QUOTA_COSTS.unlock_contact,
      preconditions: ['user.status === "active"', 'flow.recommendation.unlock'],
      effects: ['consume_quota(5)', 'webhook: deliver_contact (PII)'],
    },
    {
      name: 'employer.list_pending_claims',
      description: '列出我发布的、等待我 claim 或 reject 的 job(从猎头代建过来的)。',
      method: 'GET', path: '/v1/employer/pending-claims',
      response_schema: PendingClaimsResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"'],
      effects: ['db.jobs.listPendingClaims'],
    },
    {
      name: 'employer.claim_job',
      description: '认领一个由猎头代建的 job(把 job 状态从 open 变为 claimed)。',
      method: 'POST', path: '/v1/employer/claim-jobs/:id',
      response_schema: ClaimJobResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"', 'flow.job.claim'],
      effects: ['db.jobs.updateStatus(claimed)'],
    },
    {
      name: 'employer.reject_job',
      description: '拒绝一个由猎头代建的 job(关闭该 job)。',
      method: 'POST', path: '/v1/employer/reject-jobs/:id',
      response_schema: RejectJobResponseSchema,
      quota_cost: 0,
      preconditions: ['user.status === "active"', 'flow.job.reject'],
      effects: ['db.jobs.updateStatus(closed)'],
    },
  ],
});